### ISSUE TITLE
Linkify headers and relative paths support

### ISSUE THREAD

**Issue by DeagleGross** [borisdiakur/marked#25]
Hi! 
I am interested in using your great extension, but there are some features that are blocking our experience.

Please, could You inform me about your time management: are You still working on this project and ready to watch some pull requests? If You are, then soon we will contribute with such features:
- turn off linkify of headers (all #... are recognized as links. I can not see any possibility to turn this off)
- We are using azure Devops with TFS as repo, so in readme in TFS there are some links to files in repo (for example '[Style Format(../style.md)'). We want these links to be parsed in full links to azure devops->files path.

So, please, can You say is this possible to implement such features (by ourselves) and how long does it take for You to approve PR.
Thanks in advance.

Best regards!

**Comment by borisdiakur** [comment]
Hi.

I’m still maintaining this project, but can’t give any guarantees on response times or anything time related as I’m quite busy. It also depends on the PRs. If they are small sized, readable, include tests, that would definitely speed up things. In order to test the extension manually one has to start up the local dev environment which is a monster and super slow, even on a high performant developer machine. For what ever reason. It’s not fun. If you really need the changes urgently, you can just fork the project and publish your own extension. Afterwards you are welcome to contribute back without time pressure.
