### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by ltutar** [borisdiakur/marked#7]
Hi Boris,

One question:
I get a 404 when I click on a relative path in confluence since the link is resolved as 
https://confluence.levent.com/display/DA/doc/guides/ldap-configure-members-groups.md

In Git, I have the following text as markdown:
- In order to configure LDAP groups and members, see [LDAP guide](doc/guides/ldap-configure-members-groups.md).

Do you have any ideas to solve this issue with relative paths to other MD's and images?

Thank you in advance.

**Comment by borisdiakur** [comment]
Hi @ltutar ,
my plan was actually to keep this small plugin as stupid as possible, because I just do not have much time to maintain it (which I am really sorry about). But maybe there is someone else who would like to implement the feature, which consists of converting relative links to absolute links during rendering, and send me a PR. A good starting point would be here maybe: https://github.com/vsch/flexmark-java/issues/90
As a workaround I suggest to use absolute urls, which I know you thought about already.
I’ll try to find some slack time for this issue.
